### ISSUE TITLE
##[error]Error: The process 'sudo' failed with exit code 1

### ISSUE THREAD

**Issue by bomwo** [miloserdow/capistrano-deploy#1]
I am getting this error in your code.

```
sudo bundle install --deployment
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
	from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
	from /usr/local/bin/bundle:23:in `<main>'
##[error]Error: The process 'sudo' failed with exit code 1
##[error]Node run failed with exit code 1
```

**Comment by bomwo** [comment]
https://github.com/rbenv/rbenv/issues/1138

**Comment by miloserdow** [comment]
Hi!

Sorry for the late reply. What platform (e.g. ubuntu-latest) and version of capistrano-deploy are you using?

**Comment by bomwo** [comment]
Thanks for the answer 😄 ;
i use ubuntu-latetst version `ubuntu-latest` and capistrano-deploy version v1.3

**Comment by miloserdow** [comment]
Can you please share the failed pipeline (actual invocation of the library)?

**Comment by bomwo** [comment]
That's hard because you're using it in a private repository. 😢

**Comment by adrianthedev** [comment]
I've got the same issue

**Comment by adrianthedev** [comment]
Sorry about that. Too quick to throw the blame :) My bad 🙇 
My issue was wrong ruby version.

**Comment by adrianthedev** [comment]
This is related to https://github.com/miloserdow/capistrano-deploy/issues/2
