### ISSUE TITLE
BUNDLE_GEMFILE env variable support

### ISSUE THREAD

**Issue by deXterbed** [miloserdow/capistrano-deploy#11]
I like to keep a separate Gemfile for deployment with cap, is there a way i can specify a Gemfile e.g. Gemfile.deploy to be used when running `bundle exec cap <target> deploy` via the github action? or a group to be used from the default Gemfile?

**Comment by miloserdow** [comment]
Ok, I'll try to implement this feature this week

**Comment by miloserdow** [comment]
Now it's not the responsibility of this action, closing.
