### ISSUE TITLE
Bundle install is not using cached bundle

### ISSUE THREAD

**Issue by robzolkos** [miloserdow/capistrano-deploy#14]
The README shows a cache step before the deployment runs where the bundle is vendored to `vendor/bundle`

The `bundle install` command [here](https://github.com/miloserdow/capistrano-deploy/blob/master/lib/run.js#L30) does not have the `--path` argument set to `vendor/bundle`  therefore causing the cache to not be used at all (and a fresh bundle is installed on every deploy - taking minutes++)

Before I submit a PR was wondering if this was an oversight or am I missing a config setting somewhere?

**Comment by miloserdow** [comment]
It was an oversight but now it's not relevant any more since we stopped using `bundle install.`
