### ISSUE TITLE
Warning: The `set-env` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by C10ne** [miloserdow/capistrano-deploy#18]
When running this action I get a warning:

Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: [https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)

Not sure if it's only my setup, or a general problem with action or some of dependancies.

**Comment by soemo** [comment]
The deadline is now thw 16th of November https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/ :exclamation:

**Comment by C10ne** [comment]
Any idea how to fix this? I can't find any reference, maybe core/actions need to be updated?

**Comment by C10ne** [comment]
I verified that the issue was caused by outdated package used for @core/actions.

**Comment by miloserdow** [comment]
Thanks for your work, @C10ne!
