### ISSUE TITLE
Regression: Encrypted RSA private key file or value does not exist.

### ISSUE THREAD

**Issue by felipecsl** [miloserdow/capistrano-deploy#23]
I'm getting the message above even though the deployment seems to complete successfully.
Github ends up marking the workflow as failed though. It seems to be an issue with `working-directory`, that's my first guess. 
I'll poke around a bit
Action version 2.2

**Comment by sulmanweb** [comment]
Same Here please help
Action version master

**Comment by felipecsl** [comment]
as a temporary workaround, you can fork the action and remove the check like this https://github.com/felipecsl/capistrano-deploy/commit/d1b1341ed83e881b24b700890d86768ee0f94e0f then use your fork for now until this issue is properly fixed

**Comment by miloserdow** [comment]
I'm aiming to fix that by the end of this week

**Comment by ksz2k** [comment]
as temporary workaround, I used symlink in repo root to `${working-directory}/config`

eg. I have `working-directory: ./api`
so `ln -s api/config` helps

**Comment by miloserdow** [comment]
should be fixed by merging #17
