### ISSUE TITLE
Problem using custom working directory

### ISSUE THREAD

**Issue by bricejulia** [miloserdow/capistrano-deploy#24]
Hello,

Thanks for this project.
there seems to be a problem checking if enc_rsa_key_pth exists if a custom working directory is set.
``` javascript
if (!fs.existsSync(enc_rsa_key_pth) && !enc_rsa_key_val) {
    core.setFailed('Encrypted RSA private key file or value does not exist.');
}
```

Here we can see that we omit the custom working directory and obviously set a failed message.
But then, in the `decrypt_key` function, everything is working correctly taking into account the custom working dir.
But the initial `setFailed` call, make my CI failed

Am I missing something here ?

Thanks

**Comment by miloserdow** [comment]
Hi, this is duplicate of #23, I'm working on it.
