### ISSUE TITLE
Major version tag (v2) does not point to current release (v2.2)

### ISSUE THREAD

**Issue by n00dle** [miloserdow/capistrano-deploy#29]
Thanks for your work on this action!

The [GitHub Actions documentation](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/about-actions#using-tags-for-release-management) has this recommendation:

> Move the major version tag (such as v1, v2) to point to the Git ref of the current release.

Is it possible for you to move the `v2` tag?

**Comment by cassiompf** [comment]
Updated!

**Comment by fernandoaleman** [comment]
@cassiompf May you please also point https://github.com/miloserdow/capistrano-deploy/tree/423fcb13d34c8a1561748041252c1d130b4b509d to `v1`?

**Comment by cassiompf** [comment]
> @cassiompf May you please also point https://github.com/miloserdow/capistrano-deploy/tree/423fcb13d34c8a1561748041252c1d130b4b509d to `v1`?

Yes, I think it works too
