### ISSUE TITLE
How to setup secrets on repository?

### ISSUE THREAD

**Issue by rusikf** [miloserdow/capistrano-deploy#3]
> Save the password used in step 4 as a secret in repository settings via Settings / Secrets / Add

I am not a author of repository ( But I can contribute ), where is this settings of repository ? May be general settings https://github.com/settings/keys ?

**Comment by miloserdow** [comment]
https://github.com/<username>/<repository>/settings/secrets

**Comment by rusikf** [comment]
@miloserdow Thanks for tip :+1: , but I don't have permissions to this settings, it is possible to setup capistrano without it ?

**Comment by miloserdow** [comment]
@rusikf In such case you may clone the repository and then you will have permissions on your copy (clone). Otherwise, you may ask the person who has permission to do that step.
