### ISSUE TITLE
[Bug?] Error message "Valid ciphername values:"

### ISSUE THREAD

**Issue by adrianthedev** [miloserdow/capistrano-deploy#36]
I'm trying to encrypt my local key using the provided options and I get an error on macos Monterey. Not sure if I'm doing something wrong

![image](https://user-images.githubusercontent.com/1334409/143891086-597d836b-1430-48ed-a944-a35b8919c287.png)

**Comment by Zai** [comment]
Are you on macOS ? 

If yes try `openssl version` and if you get something like "LibreSSL" you can't use this command.
It's only working with openssl v3.

By the way we have encoded a ssh key (created from a mac with LibreSSL & ed25519) from an ubuntu server and we get an error during deployment at command `ssh-add`.
`Error loading key "config/deploy_id_rsa": error in libcrypto`

We were forced to regenerate all key directly from an ubuntu server with openssl and all works like a charm. :)

Hope it'll help to understand the problem.

**Comment by adrianthedev** [comment]
I have to admit I moved along from this project, but will reference this issue in the future when I stumble upon it.

Thank you!

**Comment by miloserdow** [comment]
I've just tested it on MacOS, seems like no longer an issue
